[colors.primary]
background = "#30302D"
foreground = "#F2F4D4"

[colors.cursor]
cursor = "#827F5A"
text = "#E9ECD4"

[colors.normal]
black = "#1F220A"
red = "#DA3842"
green = "#26AD68"
yellow = "#C4BF75"
blue = "#1184ED"
magenta = "#D685CF"
cyan = "#84E2EF"
white = "#E8E4EF"

[colors.bright]
black = "#A8A8A8"
red = "#F62138"
green = "#34EFA2"
yellow = "#E8F294"
blue = "#322AF2"
magenta = "#F2A0E8"
cyan = "#78F2FF"
white = "#FEFEFE"

[colors.dim]
black = "#100A14"
red = "#721D26"
green = "#1D7A42"
yellow = "#54542D"
blue = "#211048"
magenta = "#7A4F68"
cyan = "#467D88"
white = "#9A9A9A"

[window]
opacity = 0.8
