[colors.primary]
background = "#FFF0DF" 
foreground = "#6F5540"

[colors.cursor]
text = "#FDE8D9"
cursor = "#605040"

[colors.normal]
black = "#201008"
red = "#EF4030"
green = "#6ABF10"
yellow = "#CCCC00"
blue = "#6359F0"
magenta = "#FF28F0"
cyan = "#28F0FF"
white = "#FFFDF8"

[colors.bright]
black = "#F8F8F8"
red = "#F62138"
green = "#34EFA2"
yellow = "#E8F294"
blue = "#322AF2"
magenta = "#F2A0E8"
cyan = "#78F2FF"
white = "#FFFFFF"

[colors.dim]
black = "#100A14"
red = "#721D26"
green = "#1D7A42"
yellow = "#54542D"
blue = "#211048"
magenta = "#7A4F68"
cyan = "#467D88"
white = "#FFFFFF"

[window]
opacity = 1
