fork = false
frame = "full"
idle = true
maximized = false
mouse-cursor-icon = "arrow"
neovim-bin = "/opt/neovim/bin/nvim"
no-multigrid = false
srgb = false
tabs = true
title-hidden = false
vsync = true
wsl = false

[font]
size = 11.75

[[font.normal]]
family = "FantasqueSansM Nerd Font"
style = "ExtraLight"

[[font.bold]]
family = "FantasqueSansM Nerd Font"
style = "Normal"

[box-drawing]
# "font-glyph", "native" or "selected-native"
mode = "native"

[box-drawing.sizes]
default = [2, 4]  # Thin and thick values respectively, for all sizes

